server:
  port: 8040

spring:
  application:
    name: cloud-hystrix-server

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-cluster2:7002/eureka,http://eureka-server-cluster2:7002/eureka
