server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.19.0:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Root.123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yaoyue.cloud.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8082/eureka
      defaultZone: http://eureka-server-cluster1:7001/eureka,http://eureka-server-cluster2:7002/eureka
  instance:
    instance-id: PaymentCluster1
    prefer-ip-address: true