server:
  port: 9000

spring:
  application:
    name: cloud-alibaba-nacos-payment

  cloud:
    nacos:
      discovery:
        server-addr: 106.14.19.0:8848 #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
